title: Secure Software Design and Analysis
description: Tyler Apostolico, Will Rembish, Rob Hanna
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect
comments: true

gems:
  - jekyll-mentions
